version: '3.8'
name: app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PAYLOAD_PUBLIC_SERVER_URL: https://${DOMAIN}
        HCAPTCHA_SITE_KEY: ${HCAPTCHA_SITE_KEY}
        THEMOVIEDB_API_KEY: ${THEMOVIEDB_API_KEY}
    expose:
      - 3000
    networks:
      - traefik
      - default
    environment:
      NODE_ENV: production
      PAYLOAD_SECRET:
      PAYLOAD_PUBLIC_SERVER_URL: https://${DOMAIN}
      MONGODB_URI: mongodb://db:27017/app

      EMAIL_FROM:
      EMAIL_FROM_NAME:
      CONNECTED_EMAIL_ADDRESSES:

      SMTP_HOST:
      SMTP_PORT:
      SMTP_USER:
      SMTP_PASS:

      HCAPTCHA_SITE_KEY:
      HCAPTCHA_SECRET_KEY:

      THEMOVIEDB_API_KEY:

      TIMEZONE: Europe/Berlin

      S3_ENABLED:
      S3_BUCKET:
      S3_REGION:
      S3_ACCESS_KEY:
      S3_SECRET_KEY:
      
      # how to find it: https://www.npmjs.com/package/react-mailchimp-form
      MAILCHIMP_SIGNUP_URL:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.app.rule=(Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`))
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.app.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.app.tls.domains[0].sans=www.${DOMAIN}

      # Redirect all www to non-www middleware
      - "traefik.http.middlewares.to-nonwww.redirectregex.regex=^https?://www\\.${DOMAIN}(.*)"
      - "traefik.http.middlewares.to-nonwww.redirectregex.replacement=https://${DOMAIN}$${1}"
      - traefik.http.middlewares.to-nonwww.redirectregex.permanent=false
      - traefik.http.routers.app.middlewares=to-nonwww
    depends_on:
      - db
    restart: always
  
  db:
    image: mongo:4.4.18 # last version running without CPU flag AVX
    expose:
      - 27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
      - ./dump:/dump
    restart: always
      
networks:
  traefik:
    external: true

volumes:
  data: