packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  i18next: '^24.2.1'
  lexical: '0.21.0'
  msw: '^2.7.0'
  next: '15.1.6'
  payload: '3.21.0'
  '@payloadcms/db-mongodb': '3.21.0'
  '@payloadcms/email-nodemailer': '3.21.0'
  '@payloadcms/next': '3.21.0'
  '@payloadcms/plugin-seo': '3.21.0'
  '@payloadcms/richtext-lexical': '3.21.0'
  '@payloadcms/storage-s3': '3.21.0'
  '@payloadcms/translations': '3.21.0'
  '@payloadcms/ui': '3.21.0'

  'react': '19.0.0'
  'react-dom': '19.0.0'

  '@types/react': '^19.0.7'
  '@types/react-dom': '^19.0.3'

  unocss: '^65.4.3'
  '@unocss/reset': '^65.4.3'
  '@unocss/cli': '^65.4.3'
