packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  mongodb-memory-server: true
  msw: true
  sharp: true
catalog:
  i18next: ^26.3.0
  msw: ^2.14.6
  next: 16.2.6
  '@next/eslint-plugin-next': 16.2.6
  payload: 3.85.0
  '@payloadcms/db-mongodb': 3.85.0
  '@payloadcms/email-nodemailer': 3.85.0
  '@payloadcms/live-preview-react': 3.85.0
  '@payloadcms/next': 3.85.0
  '@payloadcms/plugin-seo': 3.85.0
  '@payloadcms/richtext-lexical': 3.85.0
  '@payloadcms/storage-s3': 3.85.0
  '@payloadcms/translations': 3.85.0
  '@payloadcms/ui': 3.85.0
  monaco-editor: ^0.55.1
  react: 19.2.6
  react-dom: 19.2.6
  '@types/react': ^19.2.15
  '@types/react-dom': ^19.2.3
  react-router: 7.16.0
  '@react-router/node': 7.16.0
  '@react-router/serve': 7.16.0
  '@react-router/dev': 7.16.0
