packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  mongodb-memory-server: true
  msw: true
  sharp: true
catalog:
  i18next: ^26.3.6
  msw: ^2.15.0
  next: 16.3.0
  '@next/eslint-plugin-next': 16.3.0
  payload: 3.87.0
  '@payloadcms/db-mongodb': 3.87.0
  '@payloadcms/email-nodemailer': 3.87.0
  '@payloadcms/live-preview-react': 3.87.0
  '@payloadcms/next': 3.87.0
  '@payloadcms/plugin-seo': 3.87.0
  '@payloadcms/richtext-lexical': 3.87.0
  '@payloadcms/storage-s3': 3.87.0
  '@payloadcms/translations': 3.87.0
  '@payloadcms/ui': 3.87.0
  monaco-editor: ^0.56.0
  react: 19.2.8
  react-dom: 19.2.8
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  react-router: 8.3.0
  '@react-router/node': 8.3.0
  '@react-router/serve': 8.3.0
  '@react-router/dev': 8.3.0
