packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  i18next: '^24.2.1'
  msw: '^2.7.0'
  next: '15.5.9'

  payload: '3.70.0'
  '@payloadcms/db-mongodb': '3.70.0'
  '@payloadcms/email-nodemailer': '3.70.0'
  '@payloadcms/live-preview-react': '3.70.0'
  '@payloadcms/next': '3.70.0'
  '@payloadcms/plugin-seo': '3.70.0'
  '@payloadcms/richtext-lexical': '3.70.0'
  '@payloadcms/storage-s3': '3.70.0'
  '@payloadcms/translations': '3.70.0'
  '@payloadcms/ui': '3.70.0'
  'monaco-editor': '^0.25.0'

  'react': '19.2.3'
  'react-dom': '19.2.3'

  '@types/react': '^19.2.3'
  '@types/react-dom': '^19.2.3'

  'react-router': '7.11.0'
  '@react-router/node': '7.11.0'
  '@react-router/serve': '7.11.0'
  '@react-router/dev': '7.11.0'

  unocss: '^66.0.0'
  '@unocss/reset': '^66.0.0'
  '@unocss/cli': '^66.0.0'
