/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    movies: Movie;
    filmPrints: FilmPrint;
    events: Event;
    screeningSeries: ScreeningSery;
    posts: Post;
    mailings: Mailing;
    media: Media;
    pages: Page;
    formats: Format;
    aspectRatios: AspectRatio;
    carriers: Carrier;
    languageVersions: LanguageVersion;
    soundFormats: SoundFormat;
    conditions: Condition;
    seasons: Season;
    genres: Genre;
    locations: Location;
    rentals: Rental;
    colors: Color;
    categories: Category;
    persons: Person;
    jobs: Job;
    companies: Company;
    countries: Country;
    navigations: Navigation;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    site: Site;
  };
  locale: 'de' | 'en';
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movies".
 */
export interface Movie {
  id: string;
  title: string;
  internationalTitle: string;
  originalTitle: string;
  tmdbId?: number | null;
  still: string | Media;
  poster: string | Media;
  directors: (string | Person)[];
  duration: number;
  ageRating?: ('0' | '6' | '12' | '16' | '18' | '') | null;
  countries: (string | Country)[];
  year: number;
  decade: number;
  isHfgProduction?: boolean | null;
  genres: (string | Genre)[];
  synopsis: string;
  trailer?: string | null;
  cast?: (string | Person)[] | null;
  crew?:
    | {
        person: string | Person;
        job: string | Job;
        id?: string | null;
      }[]
    | null;
  productionCompanies?: (string | Company)[] | null;
  tags?: string | null;
  isMigratedFromWordpress?: boolean | null;
  wordpressMigrationNotes?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  tmdbFilepath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons".
 */
export interface Person {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filmPrints".
 */
export interface FilmPrint {
  id: string;
  title?: string | null;
  movie: string | Movie;
  type?: ('analog' | 'digital') | null;
  format: string | Format;
  languageVersion: string | LanguageVersion;
  isRented?: boolean | null;
  rental?: (string | null) | Rental;
  carrier?: (string | null) | Carrier;
  category?: (string | null) | Category;
  numActs?: number | null;
  aspectRatio?: (string | null) | AspectRatio;
  color?: (string | null) | Color;
  soundFormat?: (string | null) | SoundFormat;
  condition?: (string | null) | Condition;
  url: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats".
 */
export interface Format {
  id: string;
  type?: ('analog' | 'digital') | null;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languageVersions".
 */
export interface LanguageVersion {
  id: string;
  name: string;
  abbreviation: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rentals".
 */
export interface Rental {
  id: string;
  name: string;
  logo?: (string | null) | Media;
  credits: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers".
 */
export interface Carrier {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aspectRatios".
 */
export interface AspectRatio {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soundFormats".
 */
export interface SoundFormat {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conditions".
 */
export interface Condition {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  type?: ('screening' | 'event') | null;
  title?: string | null;
  subtitle?: string | null;
  date: string;
  location?: (string | null) | Location;
  season: string | Season;
  series?: (string | null) | ScreeningSery;
  header?: (string | null) | Media;
  poster?: (string | null) | Media;
  info?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  films?:
    | {
        filmprint: string | FilmPrint;
        isSupportingFilm?: boolean | null;
        info?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  moderator?: string | null;
  guest?: string | null;
  excludeFromUpcoming?: boolean | null;
  url: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name?: string | null;
  default?: boolean | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: string;
  name: string;
  header: string | Media;
  sort?: string | null;
  url: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screeningSeries".
 */
export interface ScreeningSery {
  id: string;
  name: string;
  hero?: {
    type?: ('image' | 'headline' | 'none') | null;
    headline?: string | null;
    image?: (string | null) | Media;
  };
  blocks?:
    | (
        | ContentBlockType
        | GalleryBlockType
        | ImageBlockType
        | VideoBlockType
        | EventsBlockType
        | RawHTMLBlockType
        | KronolithCalendarEmbedBlockType
      )[]
    | null;
  url: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockType".
 */
export interface ContentBlockType {
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockType".
 */
export interface GalleryBlockType {
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockType".
 */
export interface ImageBlockType {
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockType".
 */
export interface VideoBlockType {
  url: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsBlockType".
 */
export interface EventsBlockType {
  type: 'manual' | 'screeningSeries';
  events?:
    | {
        doc: string | Event;
        id?: string | null;
      }[]
    | null;
  screeningSeries?: (string | null) | ScreeningSery;
  id?: string | null;
  blockName?: string | null;
  blockType: 'events';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RawHTMLBlockType".
 */
export interface RawHTMLBlockType {
  html: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rawHTML';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KronolithCalendarEmbedBlockType".
 */
export interface KronolithCalendarEmbedBlockType {
  url: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'kronolithCalendarEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  date: string;
  header: string | Media;
  link?: {
    type?: ('none' | 'internal' | 'external') | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'events';
          value: string | Event;
        } | null)
      | ({
          relationTo: 'screeningSeries';
          value: string | ScreeningSery;
        } | null)
      | ({
          relationTo: 'filmPrints';
          value: string | FilmPrint;
        } | null)
      | ({
          relationTo: 'seasons';
          value: string | Season;
        } | null);
    url?: string | null;
  };
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  details?: (ContentBlockType | ImageBlockType | GalleryBlockType | VideoBlockType)[] | null;
  url: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  layoutType?: ('default' | 'info') | null;
  hero?: {
    type?: ('image' | 'headline' | 'none') | null;
    headline?: string | null;
    image?: (string | null) | Media;
  };
  blocks?:
    | (
        | ContentBlockType
        | GalleryBlockType
        | ImageBlockType
        | VideoBlockType
        | EventsBlockType
        | RawHTMLBlockType
        | KronolithCalendarEmbedBlockType
      )[]
    | null;
  url: string;
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailings".
 */
export interface Mailing {
  id: string;
  subject: string;
  color?: string | null;
  language?: ('en' | 'de') | null;
  header?: {
    image?: (string | null) | Media;
    overlay?: (string | null) | Media;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  footer?: {
    image?: (string | null) | Media;
    label?: string | null;
    link?: string | null;
  };
  html?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigations".
 */
export interface Navigation {
  id: string;
  type: 'main' | 'mobile' | 'footer' | 'socialMedia' | 'subnavigation';
  items?:
    | {
        type?: ('internal' | 'external' | 'subnavigation' | 'language') | null;
        name?: string | null;
        page?: (string | null) | Page;
        relPath?: string | null;
        url?: string | null;
        icon?: (string | null) | Media;
        subnavigation?: (string | null) | Navigation;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'movies';
        value: string | Movie;
      } | null)
    | ({
        relationTo: 'filmPrints';
        value: string | FilmPrint;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'screeningSeries';
        value: string | ScreeningSery;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'mailings';
        value: string | Mailing;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'formats';
        value: string | Format;
      } | null)
    | ({
        relationTo: 'aspectRatios';
        value: string | AspectRatio;
      } | null)
    | ({
        relationTo: 'carriers';
        value: string | Carrier;
      } | null)
    | ({
        relationTo: 'languageVersions';
        value: string | LanguageVersion;
      } | null)
    | ({
        relationTo: 'soundFormats';
        value: string | SoundFormat;
      } | null)
    | ({
        relationTo: 'conditions';
        value: string | Condition;
      } | null)
    | ({
        relationTo: 'seasons';
        value: string | Season;
      } | null)
    | ({
        relationTo: 'genres';
        value: string | Genre;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'rentals';
        value: string | Rental;
      } | null)
    | ({
        relationTo: 'colors';
        value: string | Color;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'persons';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'countries';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'navigations';
        value: string | Navigation;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: string;
  logo?: (string | null) | Media;
  logoMobile?: (string | null) | Media;
  favicon?: (string | null) | Media;
  footerContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location: {
    country: string | Country;
    region: string;
    city: string;
    zip: string;
    street: string;
    name: string;
    latitude: string;
    longitude: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}