apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kino-frontend
  namespace: kino-im-blauen-salon
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kinoimblauensalon.de
        - www.kinoimblauensalon.de
      secretName: kinoimblauensalon-de-tls
  rules:
    - host: kinoimblauensalon.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kino-frontend
                port:
                  name: http
    - host: www.kinoimblauensalon.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kino-frontend
                port:
                  name: http
