apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-ingress.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml
